# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  # rspec-expectations config goes here. You can use an alternate
  # assertion/expectation library such as wrong or the stdlib/minitest
  # assertions if you prefer.
  config.expect_with :rspec do |expectations|
    # This option will default to `true` in RSpec 4. It makes the `description`
    # and `failure_message` of custom matchers include text for helper methods
    # defined using `chain`, e.g.:
    #     be_bigger_than(2).and_smaller_than(4).description
    #     # => "be bigger than 2 and smaller than 4"
    # ...rather than:
    #     # => "be bigger than 2"
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  # This option will default to `:apply_to_host_groups` in RSpec 4 (and will
  # have no way to turn it off -- the option exists only for backwards
  # compatibility in RSpec 3). It causes shared context metadata to be
  # inherited by the metadata hash of host groups and examples, rather than
  # triggering implicit auto-inclusion in groups with matching metadata.
  config.shared_context_metadata_behavior = :apply_to_host_groups

# The settings below are suggested to provide a good initial experience
# with RSpec, but feel free to customize to your heart's content.
=begin
  # This allows you to limit a spec run to individual examples or groups
  # you care about by tagging them with `:focus` metadata. When nothing
  # is tagged with `:focus`, all examples get run. RSpec also provides
  # aliases for `it`, `describe`, and `context` that include `:focus`
  # metadata: `fit`, `fdescribe` and `fcontext`, respectively.
  config.filter_run_when_matching :focus

  # Allows RSpec to persist some state between runs in order to support
  # the `--only-failures` and `--next-failure` CLI options. We recommend
  # you configure your source control system to ignore this file.
  config.example_status_persistence_file_path = "spec/examples.txt"

  # Limits the available syntax to the non-monkey patched syntax that is
  # recommended. For more details, see:
  # https://relishapp.com/rspec/rspec-core/docs/configuration/zero-monkey-patching-mode
  config.disable_monkey_patching!

  # Many RSpec users commonly either run the entire suite or an individual
  # file, and it's useful to allow more verbose output when running an
  # individual spec file.
  if config.files_to_run.one?
    # Use the documentation formatter for detailed output,
    # unless a formatter has already been configured
    # (e.g. via a command-line flag).
    config.default_formatter = "doc"
  end

  # Print the 10 slowest examples and example groups at the
  # end of the spec run, to help surface which specs are running
  # particularly slow.
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random

  # Seed global randomization in this process using the `--seed` CLI option.
  # Setting this allows you to use `--seed` to deterministically reproduce
  # test failures related to randomization by passing the same `--seed` value
  # as the one that triggered the failure.
  Kernel.srand config.seed
=end
end

def test_data
  @student1 = Student.create!(name: "Penelope")
  @student2 = Student.create!(name: "Peter")
  @student3 = Student.create!(name: "Pepe")
  @student4 = Student.create!(name: "Parth")
  @student5 = Student.create!(name: "Priscilla")
  @student6 = Student.create!(name: "Pablo")
  @student7 = Student.create!(name: "Puja")
  @student8 = Student.create!(name: "Patricia")
  @student9 = Student.create!(name: "Piper")
  @student10 = Student.create!(name: "Paula")
  @student11 = Student.create!(name: "Pamela")
  @student12 = Student.create!(name: "Paige")
  @student13 = Student.create!(name: "Peggy")
  @student14 = Student.create!(name: "Pedro")
  @student15 = Student.create!(name: "Phoebe")
  @student16 = Student.create!(name: "Pajak")
  @student17 = Student.create!(name: "Parker")
  @student18 = Student.create!(name: "Priyal")
  @student19 = Student.create!(name: "Paxton")
  @student20 = Student.create!(name: "Patrick")

  @teacher1 = Teacher.create!(name: "Phillips", room_number: 456)
  @teacher2 = Teacher.create!(name: "Vandergrift", room_number: 120)
  @teacher3 = Teacher.create!(name: "Mauch", room_number: 101)
  @teacher4 = Teacher.create!(name: "Patel", room_number: 320)
  @teacher5 = Teacher.create!(name: "Marquez", room_number: 560)
  @teacher6 = Teacher.create!(name: "Boykin", room_number: 200)
  @teacher7 = Teacher.create!(name: "Phlop", room_number: 333)
  @teacher8 = Teacher.create!(name: "Pendergrass", room_number: 222)
  @teacher9 = Teacher.create!(name: "Palomo", room_number: 323)
  @teacher10 = Teacher.create!(name: "Altshuler", room_number: 543)
  @teacher11 = Teacher.create!(name: "Aleman", room_number: 187)
  @teacher12 = Teacher.create!(name: "Ashley", room_number: 432)
  @teacher13 = Teacher.create!(name: "Bonacci", room_number: 399)
  @teacher14 = Teacher.create!(name: "Brazukas", room_number: 287)
  @teacher15 = Teacher.create!(name: "Brockington", room_number: 299)
  @teacher16 = Teacher.create!(name: "Brizuela", room_number: 376)
  @teacher17 = Teacher.create!(name: "Burkhart", room_number: 199)
  @teacher18 = Teacher.create!(name: "Choi", room_number: 463)
  @teacher19 = Teacher.create!(name: "Shah", room_number: 354)
  @teacher20 = Teacher.create!(name: "Dimaggio", room_number: 251)

  @course1 = Course.create!(name: "Cooking Pasta", teacher: @teacher1)
  @course2 = Course.create!(name: "Yoga", teacher: @teacher1)
  @course3 = Course.create!(name: "How to Guitar", teacher: @teacher2)
  @course4 = Course.create!(name: "Gym", teacher: @teacher3)
  @course5 = Course.create!(name: "Football", teacher: @teacher4)
  @course6 = Course.create!(name: "Calculus", teacher: @teacher5)
  @course7 = Course.create!(name: "Fruit", teacher: @teacher6)
  @course8 = Course.create!(name: "Social Studies", teacher: @teacher7)
  @course9 = Course.create!(name: "English", teacher: @teacher8)
  @course10 = Course.create!(name: "Programming", teacher: @teacher9)
  @course11 = Course.create!(name: "Singing", teacher: @teacher10)
  @course12 = Course.create!(name: "Fashion", teacher: @teacher11)

  Enrollment.create!(student: @student1, course: @course1, grade: 60)
  Enrollment.create!(student: @student2, course: @course2, grade: 70)
  Enrollment.create!(student: @student2, course: @course4, grade: 100)
  Enrollment.create!(student: @student3, course: @course2, grade: 74)
  Enrollment.create!(student: @student4, course: @course3, grade: 82)
  Enrollment.create!(student: @student5, course: @course3, grade: 45)
  Enrollment.create!(student: @student5, course: @course4, grade: 50)
  Enrollment.create!(student: @student7, course: @course11, grade: 62)
  Enrollment.create!(student: @student7, course: @course10, grade: 76)
  Enrollment.create!(student: @student7, course: @course9, grade: 81)
  Enrollment.create!(student: @student7, course: @course8, grade: 91)
  Enrollment.create!(student: @student8, course: @course8, grade: 84)
  Enrollment.create!(student: @student9, course: @course8, grade: 88)
  Enrollment.create!(student: @student9, course: @course7, grade: 83)
  Enrollment.create!(student: @student10, course: @course7, grade: 93)
  Enrollment.create!(student: @student10, course: @course5, grade: 95)
  Enrollment.create!(student: @student11, course: @course5, grade: 95)
  Enrollment.create!(student: @student11, course: @course11, grade: 80)
  Enrollment.create!(student: @student11, course: @course6, grade: 95)
  Enrollment.create!(student: @student11, course: @course1, grade: 94)
  Enrollment.create!(student: @student11, course: @course2, grade: 60)
  Enrollment.create!(student: @student12, course: @course6, grade: 55)
  Enrollment.create!(student: @student13, course: @course7, grade: 97)
  Enrollment.create!(student: @student14, course: @course10, grade: 86)
  Enrollment.create!(student: @student15, course: @course9, grade: 77)
  Enrollment.create!(student: @student15, course: @course4, grade: 93)
  Enrollment.create!(student: @student15, course: @course1, grade: 73)
  Enrollment.create!(student: @student16, course: @course2, grade: 79)
  Enrollment.create!(student: @student16, course: @course6, grade: 73)
  Enrollment.create!(student: @student17, course: @course7, grade: 86)
  Enrollment.create!(student: @student17, course: @course8, grade: 91)
  Enrollment.create!(student: @student17, course: @course9, grade: 93)
  Enrollment.create!(student: @student18, course: @course10, grade: 94)
  Enrollment.create!(student: @student19, course: @course4, grade: 84)
  Enrollment.create!(student: @student20, course: @course1, grade: 85)
  Enrollment.create!(student: @student20, course: @course11, grade: 89)
  Enrollment.create!(student: @student20, course: @course3, grade: 98)
end